/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as AppWarehouseImport } from './routes/_app/_warehouse'
import { Route as AppWarehouseRemainsImport } from './routes/_app/_warehouse/remains'
import { Route as AppWarehouseProductsImport } from './routes/_app/_warehouse/products'
import { Route as AppWarehousePartiesImport } from './routes/_app/_warehouse/parties'
import { Route as AppWarehouseOrdersImport } from './routes/_app/_warehouse/orders'
import { Route as AppWarehouseOrdersOrderIdEditImport } from './routes/_app/_warehouse/orders_/$orderId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppWarehouseRoute = AppWarehouseImport.update({
  id: '/_warehouse',
  getParentRoute: () => AppRoute,
} as any)

const AppWarehouseRemainsRoute = AppWarehouseRemainsImport.update({
  id: '/remains',
  path: '/remains',
  getParentRoute: () => AppWarehouseRoute,
} as any)

const AppWarehouseProductsRoute = AppWarehouseProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppWarehouseRoute,
} as any)

const AppWarehousePartiesRoute = AppWarehousePartiesImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppWarehouseRoute,
} as any)

const AppWarehouseOrdersRoute = AppWarehouseOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppWarehouseRoute,
} as any)

const AppWarehouseOrdersOrderIdEditRoute =
  AppWarehouseOrdersOrderIdEditImport.update({
    id: '/orders_/$orderId/edit',
    path: '/orders/$orderId/edit',
    getParentRoute: () => AppWarehouseRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/_warehouse': {
      id: '/_app/_warehouse'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppWarehouseImport
      parentRoute: typeof AppImport
    }
    '/_app/_warehouse/orders': {
      id: '/_app/_warehouse/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppWarehouseOrdersImport
      parentRoute: typeof AppWarehouseImport
    }
    '/_app/_warehouse/parties': {
      id: '/_app/_warehouse/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppWarehousePartiesImport
      parentRoute: typeof AppWarehouseImport
    }
    '/_app/_warehouse/products': {
      id: '/_app/_warehouse/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppWarehouseProductsImport
      parentRoute: typeof AppWarehouseImport
    }
    '/_app/_warehouse/remains': {
      id: '/_app/_warehouse/remains'
      path: '/remains'
      fullPath: '/remains'
      preLoaderRoute: typeof AppWarehouseRemainsImport
      parentRoute: typeof AppWarehouseImport
    }
    '/_app/_warehouse/orders_/$orderId/edit': {
      id: '/_app/_warehouse/orders_/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof AppWarehouseOrdersOrderIdEditImport
      parentRoute: typeof AppWarehouseImport
    }
  }
}

// Create and export the route tree

interface AppWarehouseRouteChildren {
  AppWarehouseOrdersRoute: typeof AppWarehouseOrdersRoute
  AppWarehousePartiesRoute: typeof AppWarehousePartiesRoute
  AppWarehouseProductsRoute: typeof AppWarehouseProductsRoute
  AppWarehouseRemainsRoute: typeof AppWarehouseRemainsRoute
  AppWarehouseOrdersOrderIdEditRoute: typeof AppWarehouseOrdersOrderIdEditRoute
}

const AppWarehouseRouteChildren: AppWarehouseRouteChildren = {
  AppWarehouseOrdersRoute: AppWarehouseOrdersRoute,
  AppWarehousePartiesRoute: AppWarehousePartiesRoute,
  AppWarehouseProductsRoute: AppWarehouseProductsRoute,
  AppWarehouseRemainsRoute: AppWarehouseRemainsRoute,
  AppWarehouseOrdersOrderIdEditRoute: AppWarehouseOrdersOrderIdEditRoute,
}

const AppWarehouseRouteWithChildren = AppWarehouseRoute._addFileChildren(
  AppWarehouseRouteChildren,
)

interface AppRouteChildren {
  AppWarehouseRoute: typeof AppWarehouseRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWarehouseRoute: AppWarehouseRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppWarehouseRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof AppWarehouseOrdersRoute
  '/parties': typeof AppWarehousePartiesRoute
  '/products': typeof AppWarehouseProductsRoute
  '/remains': typeof AppWarehouseRemainsRoute
  '/orders/$orderId/edit': typeof AppWarehouseOrdersOrderIdEditRoute
}

export interface FileRoutesByTo {
  '': typeof AppWarehouseRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof AppWarehouseOrdersRoute
  '/parties': typeof AppWarehousePartiesRoute
  '/products': typeof AppWarehouseProductsRoute
  '/remains': typeof AppWarehouseRemainsRoute
  '/orders/$orderId/edit': typeof AppWarehouseOrdersOrderIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_warehouse': typeof AppWarehouseRouteWithChildren
  '/_app/_warehouse/orders': typeof AppWarehouseOrdersRoute
  '/_app/_warehouse/parties': typeof AppWarehousePartiesRoute
  '/_app/_warehouse/products': typeof AppWarehouseProductsRoute
  '/_app/_warehouse/remains': typeof AppWarehouseRemainsRoute
  '/_app/_warehouse/orders_/$orderId/edit': typeof AppWarehouseOrdersOrderIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/orders'
    | '/parties'
    | '/products'
    | '/remains'
    | '/orders/$orderId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/orders'
    | '/parties'
    | '/products'
    | '/remains'
    | '/orders/$orderId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_warehouse'
    | '/_app/_warehouse/orders'
    | '/_app/_warehouse/parties'
    | '/_app/_warehouse/products'
    | '/_app/_warehouse/remains'
    | '/_app/_warehouse/orders_/$orderId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/login"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_warehouse"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_app/_warehouse": {
      "filePath": "_app/_warehouse.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_warehouse/orders",
        "/_app/_warehouse/parties",
        "/_app/_warehouse/products",
        "/_app/_warehouse/remains",
        "/_app/_warehouse/orders_/$orderId/edit"
      ]
    },
    "/_app/_warehouse/orders": {
      "filePath": "_app/_warehouse/orders.tsx",
      "parent": "/_app/_warehouse"
    },
    "/_app/_warehouse/parties": {
      "filePath": "_app/_warehouse/parties.tsx",
      "parent": "/_app/_warehouse"
    },
    "/_app/_warehouse/products": {
      "filePath": "_app/_warehouse/products.tsx",
      "parent": "/_app/_warehouse"
    },
    "/_app/_warehouse/remains": {
      "filePath": "_app/_warehouse/remains.tsx",
      "parent": "/_app/_warehouse"
    },
    "/_app/_warehouse/orders_/$orderId/edit": {
      "filePath": "_app/_warehouse/orders_/$orderId/edit.tsx",
      "parent": "/_app/_warehouse"
    }
  }
}
ROUTE_MANIFEST_END */
